### ISSUE TITLE
Accessing private parts of datasketches

### ISSUE THREAD

**Issue by AlexanderSaydakov** [apache/druid#12261] opened 2022-02-15 01:54 UTC
We have noticed this recent change https://github.com/apache/druid/commit/e648b01afba52ee5b980d28b16b636e346a86819

This change introduced a piece of code which bypasses public API of DataSketches and accesses a private part of implementation.

https://github.com/apache/druid/blob/033989eb1d8f4f91268b2d7d4d3dc73af7bf2c3f/extensions-core/datasketches/src/main/java/org/apache/druid/query/aggregation/datasketches/theta/SketchAggregator.java#L60

We believe that it is problematic and can lead to wrong results.
We have this in our documentation:
/**
  * Although the gadget object is initially an UpdateSketch, in the context of a Union it is used
  * as a specialized buffer that happens to leverage much of the machinery of an UpdateSketch.
  * However, in this context some of the key invariants of the sketch algorithm are intentionally
  * violated as an optimization. As a result this object can not be considered as an UpdateSketch
  * and should never be exported as an UpdateSketch. It’s internal state is not necessarily
  * finalized and may contain garbage. Also its internal concept of “nominal entries” or “k” can
  * be meaningless. It is private for very good reasons.
  */

**Comment by kfaraz** [comment] 2022-02-15 17:57
Thanks a lot for pointing this out, @AlexanderSaydakov ! I had missed this while making the changes in the mentioned commit.

What I really intended to do was get a better estimate of the memory used by a `org.apache.datasketches.theta.Union`.
As the `Union` interface does not expose a `getCurrentBytes()` or similar method, I had to resort to the reflection.

Please advise what would be a better way to achieve the same.

**Comment by gianm** [comment] 2022-02-15 20:52
> PLEASE, engage with us and help us understand what it is you are trying to do. If it means adding a public API to accomplish it, we are more than willing to do that.

Please don't take it personally that nobody reached out to you about the original problem. The Druid project is a big place with a lot of dependencies, and not all contributors are aware of how willing those various dependencies' maintainers are to work with us. Your willingness to work with us over the years is very much appreciated, as is the fact that you took the time to write up your concerns about this particular case.

> The memory currently being used by a Union or Sketch is rather complex.

The commit is from #12073, #12022 which are trying to improve memory estimation in the on-heap indexing implementation. The goal of the patch is to decide when to spill an on-heap index to disk. To do this properly, we need a way to estimate the memory usage of the index. The patch works by adding an `aggregateWithSize()` method to on-heap aggregators that (1) does an aggregation and (2) returns the amount of additional memory use caused by that particular aggregation. Each aggregator is associated with a particular row in the index, so we then sum up the memory used by all aggregators in all rows to get the memory footprint of the entire index.

The private field in this case is being used by SketchAggregator to implement the memory-estimation piece of `aggregateWithSize()`.

We shouldn't be using private fields like that, so we should find another way to solve the original problem.

One obvious solution I can think of is to use a simple formula, like something that is based only on the `size` parameter and the number of items added so far. I'm not sure how accurate this would be since I'm not super familiar with how the sketches internally manage their on-heap memory. But maybe it'd be close enough? If we do go this way, an implementation note: at ingestion time, it's likely that a small number of items get added to each sketch. (Like in the 1 to 50 range.) I think some sketches have a special mode they use when the number of added items is low, and whenever that is true, we'd want to take that into account to avoid overcounting memory usage.

@AlexanderSaydakov or @leerho do you have any other, better suggestions? & @kfaraz could you please work with them to implement a better solution when we come up with one?

**Comment by imply-cheddar** [comment] 2022-02-15 22:37
As gian mentioned, the code is reaching in and grabbing the _gadget as a short-term solution to grab the number of bytes used.  It would absolutely be preferable for the UnionSketch to also expose the same `.getCurrentBytes()` method.

In terms of the implementation, the sketch that was grabbed is only being used to call `.getCurrentBytes()` and is used for no other purpose.  The memory counting structure works with deltas, so if reset was called and the number got smaller, there would then be a negative delta in memory usage and the memory consumption values would be updated accordingly.  

The intention was always to open a ticket to request that the public API be extended.  We wanted to have a concrete example of why we needed the method rather than just asking for a random method, so we wanted the PR to actually exist before doing the request.  In the end, the request back to the datasketches got lost in the shuffle of getting the interface changes worked out, so that's our bad.

**Comment by leerho** [comment] 2022-02-16 04:52
I have added a PR, mentioned just above, to directly address this issue.  It will be released with the next Java release which should be relatively soon since we also want to release a new KllDoublesSketch, plus a few other things.  

I do respectfully request that you do not lock your "short-term" solution in a formal release.  

Please note: the getCurrentBytes() method implemented here as well as in your "short-term" solution will only report a different value after the internal gadget goes through a resize when the current internal hash table is full. In between these resize events this method will return the value from the previous resize event.   If you serialize the union via toByteArray() the length of the byte array will exactly be the value returned by this method.  It also represents (approximately) how much RAM the union is using.  

However, if you do union.toByteArray(union.getResult()), the size will generally be much smaller as the union has been "pulled back to K" and compacted.  

We don't recommend that you actually serialize the union to either store to disk or to transport to another machine because it is so much larger than the compact sketch you get when you getResult().

**Comment by imply-cheddar** [comment] 2022-02-16 10:34
The value is currently being used to estimate the total size in memory of the onheap Aggregator object, so the semantics that you mentioned are exactly what we want.  It's never used to determine or allocate the number of bytes actually required to store, persist or transport the sketch.

It's also perfectly fine that it doesn't always produce a new value.  That's understood and accounted for.

Thanks for such a quick turnaround on an update to the base library.  As soon as that's release, let us know and we will update the code to remove the reflection.

**Comment by leerho** [comment] 2022-04-22 00:48
@gianm @imply-cheddar @kfaraz 

This is to let you know that [datasketches-java 3.2.0-RC1](https://lists.apache.org/thread/2ft96szssk29sglgsrofzdbh25jntr43) is up for vote.  This release contains two important features requested by Druid or Druid users:

- This release extends the quantiles KLL sketch to include both doubles
and float types as well as full updatable operation off-heap in contiguous memory.
 - This release also adds two new methods to Theta Union based on the
discussion on Druid issue # 12261:
    - getCurrentBytes() This behaves similarly to the Theta Sketch method
by the same name.
    - getMaxUnionBytes() This behaves similarly to the static Theta / Sketches
method by the same name, but is non-static and returns the maximum stored
bytes for this union given its nominal entries configuration.

If you would like to vote, please do :)

Thanks,
Lee.

**Comment by leerho** [comment] 2022-04-22 00:50
Also, @AlexanderSaydakov is working to extend the DataSketches Druid adaptor to accommodate the new KllSketch.

**Comment by leerho** [comment] 2022-04-22 18:14
@gianm @imply-cheddar @kfaraz

Question:
With the new datasketches-java 3.2.0-RC1 that is in vote right now, it is not possible to merge a KllFloatsSketch into a KllDoublesSketch as it will throw an error. Even if this were possible, you would naturally lose some accuracy (at the primitive level) going from a float to a double.  Nevertheless, it would be relatively straightforward to create a "converter tool" that would create a KllDoublesSketch from a KllFloatsSketch that one could use before a merge.    Is such a capability of interest in the Druid community?  If so, could it wait until the next datasketches-java release?

**Comment by gianm** [comment] 2022-05-09 15:57
> With the new datasketches-java 3.2.0-RC1 that is in vote right now, it is not possible to merge a KllFloatsSketch into a KllDoublesSketch as it will throw an error. Even if this were possible, you would naturally lose some accuracy (at the primitive level) going from a float to a double. Nevertheless, it would be relatively straightforward to create a "converter tool" that would create a KllDoublesSketch from a KllFloatsSketch that one could use before a merge. Is such a capability of interest in the Druid community? If so, could it wait until the next datasketches-java release?

If we're going to support using both at ingestion time, then I think a converter would be useful, since that would allow people to switch from the float sketch to the double sketch without creating a new column. However, I don't think it's essential enough to block datasketches-java releases. We will just need to document that at the current time, if you want to switch KLL sketch implementations, you should create a new column, and you can't merge sketches of two different types.

**Comment by gianm** [comment] 2022-05-09 15:58
@abhishekagarwal87 fyi, I tagged this with 0.23.0 due to the discussion above. I hope we can include this change.

**Comment by abhishekagarwal87** [comment] 2022-05-10 12:21
Sure thing, @gianm.

**Comment by abhishekagarwal87** [comment] 2022-05-17 08:26
This is fixed by #12522 #12509

**Closed by abhishekagarwal87** 2022-05-17 08:26 UTC
