### ISSUE TITLE
Issue with PostAggregator arrayOfDoublesSketchConstant in latest Druid 29.0.1

### ISSUE THREAD

**Issue by anshu-makkar** [apache/druid#16539] opened 2024-06-03 14:32 UTC
Getting Exception when using PostAggregator `arrayOfDoublesSketchConstant` in the groupby Query. 

### Affected Version

Currently running, Druid version 25.0.0 with custom jar for Datasketches, trying to use the latest druid with postaggregator `arrayOfDoublesSketchConstant`

### Description

Getting an exception : 
```
{
    "error": "Unknown exception",
    "errorMessage": "Unhandled exception made it to the top",
    "errorClass": "com.fasterxml.jackson.databind.exc.ValueInstantiationException",
    "host": "X.X.X.X"
}
```

Example Query 
```
{
    "dataSource": {
        "type": "table",
        "name": "brq"
    },
    "context": {
        "queryId": "4d516332-92f3-4f6b-a19f-760f0865653d",
        "timeout": 120000
    },
    "queryType": "groupBy",
    "intervals": [
        "2024-05-23T00:00:00.000Z/2024-06-02T00:00:00.000Z"
    ],
    "granularity": "hour",
    "filter": {
        "type": "and",
        "fields": [
            {
                "type": "and",
                "fields": [
                    {
                        "type": "selector",
                        "dimension": "exc",
                        "value": 6
                    },
                    {
                        "type": "and",
                        "fields": [
                            {
                                "type": "selector",
                                "dimension": "country",
                                "value": "US"
                            }
                ]
            },
            {
                "type": "in",
                "dimension": "types",
                "values": [
                    "5"
                ]
            }
        ]
    },
    "aggregations": [
        {
            "type": "arrayOfDoublesSketch",
            "name": "tuple_sketch_agg",
            "fieldName": "tuple_sketch_count"
        }
    ],
    "postAggregations": [
        {
            "type": "arrayOfDoublesSketchToMetricsSumEstimate",
            "name": "psids_tuple_sketch_metric_estimate",
            "field": {
                "type": "arrayOfDoublesSketchSetOp",
                "name": "tuple_sketch_set_ops",
                "operation": "INTERSECT",
                "fields": [
                    {
                        "type": "fieldAccess",
                        "name": "tuple_sketch_post_agg",
                        "fieldName": "tuple_sketch_agg"
                    },
                    {
                        "type": "arrayOfDoublesSketchConstant",
                        "name": "tuple_sketch_const_post_agg",
                        "value": "AQEJAwgBzJP/////////fyMAAAAAAAAAjBCbsE9M6x0OgYV+hyEhMxPw94jlVLRXGyO4rtPzLWYcnHztRP9Wd58FyDQEmRw2ofL5I83Ee3Ik9kmVt7h8c03WBgoFokEcpycf1NYBADgwuTxsghD+KTEcUTzHx95aPNULnBE3Jza9Nop6/YRldD5W5wISgod3wGaHm9fZaBDFTp22xM8mI0jxq5WQp6RBSnjyU1z9RShIAeGt6GwKClGIUp5AqJVK1MFkXNeS2B5ZznJuo/qJN+JPO+Tn1vtp4+u6RbBYliZiAfvzgBPFb2lOrcJkcM5Z612tuz97oHtt+2A/19TsMe/Z9PqIkIx5cSdC+RGmeSj0gehVsshlW/aioTu5KRY5+uSCBGkhFW7KrLuqHsgydwAAAAAAAPA/AAAAAAAAQ0AAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAQAAAAAAAAABAAAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAAAIQAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAAAEAAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAAhAAAAAAAAACEA="
                    }
                ],
            }
        }
    ],
    "dimensions": []
}
```

`tuple_sketch_count` is a column which is of type ArrayofDoubleSketch

**Comment by gianm** [comment] 2024-06-05 04:50
Could you please add `"debug": true` to your query context and find the stack trace on the `host` that the error message mentions? (It might be a Broker or it might be a data server.)

**Comment by gianm** [comment] 2024-06-05 05:09
Nvm, I think I see what the issue is. Raised a PR: #16550.

**Comment by anshu-makkar** [comment] 2024-06-05 05:16
Thanks @gianm, When can we expect a release with this fix, We wanted to upgrade to latest version of druid to use MSQ for ingestion.

**Comment by cryptoe** [comment] 2024-06-05 05:28
@anshu-makkar The fix would be part of druid 31 which would be released in Aug/September. You can always compile your own distribution if you need the patch earlier than that. The backport on top of 29.0.1 or 30.0.0 would not have any conflicts.

**Comment by frankgrimes97** [comment] 2024-06-05 15:50
@cryptoe Any chance a `29.0.2` or even a `30.0.0-rc3` release could be cut with this fix (once approved/CI tested/merged to `master` on PR-16550?
Choosing between waiting until a September `31.0.0` release and forking/building our own distribution image for a bugfix feels a bit painful. 😄
Thanks!

**Closed** 2024-06-06 03:01 UTC
Labels: Uncategorized problem report
