### ISSUE TITLE
Expressions within aggregations can no longer use virtual columns

### ISSUE THREAD

**Issue by dylwylie** [apache/druid#8970] opened 2019-11-28 19:51 UTC
### Affected Version

0.15.0-incubating
0.15.1-incubating
0.16.0-incubating

### Description

Prior to 0.15.0, an expression within an aggregation could use a virtual column. In later versions it seems that a virtual column used within another expression will always evaluate to 0.

This was useful as it allowed expressions using _time to be evaluated once per segment (within a virtual column) rather than evaluating it every aggregation operation.

I'm still trying to decipher why but it looks like when the virtual column selector is loaded, the returned value is a "ArrayExprEval" which has a hardcoded value of 0 for asLong.

bit of a contrived example but to show what's changed

`{
  "dataSource" : "test",
  "intervals" : [
    "2019-11-01/2019-11-02"
  ],
  "granularity" : "all",
  "aggregations" : [
    {
      "type" : "longSum",
      "name" : "computed_value",
      "expression" : "1 + two"
    }
  ],
  "virtualColumns" : [
    {
      "name" : "two",
      "expression" : "2",
      "type" : "expression"
    }
  ],
  "queryType" : "timeseries"
}`

returns 

`[
    {
        "timestamp": "2019-11-01T00:00:00.000Z",
        "result": {
            "computed_value": 1574832721
        }
    }
]`

on 0.14.2

but 

`
[
    {
        "timestamp": "2019-11-01T00:00:00.000Z",
        "result": {
            "computed_value": 0
        }
    }
]
`
on 0.16.0

**Comment by bbecker-te** [comment] 2021-04-29 21:14
Is this still an issue. We are seeing a strange issue where virtual columns are 0 in recent data, then get a value later. This is using Druid 20.0.

**Comment by clintropolis** [comment] 2021-04-29 21:22
Oops, I missed this issue when it was reported, this seems related to expression support for multi-value string columns and the array expressions which came with it. I'll have a look and see if this is still an issue and if I can spot what might be going on.

> Is this still an issue. We are seeing a strange issue where virtual columns are 0 in recent data, then get a value later. This is using Druid 20.0.

By recent data, do you mean realtime queries?

**Comment by mishmam3** [comment] 2021-04-29 21:42
Yes, it looks like only recent data is affected (most recent 10 minutes). One workaround is to use filtered aggregations for certain queries, but very strange that either using a virtual column or an expression in an aggregation doesn't return the correct results. We do rely on virtual columns for a bunch of queries though. 

The results for virtual column aggregation queries seem to get updated every 10 minutes. I was wondering if there is some background process running every 10 minutes that updates something, seems unlikely though. 

We tested this with caching disabled by setting `useCache` to false in the native query.

**Comment by bbecker-te** [comment] 2021-04-29 21:56
Here is an example of our problem:
```
{
   "queryType": "groupBy",
   "dataSource":  "cea_http_1m",
   "intervals": {
      "type": "intervals",
      "intervals": [
        "2021-04-29T21:30:00.000Z/2021-04-29T22:00:00.001Z"
      ]
    },

   "granularity": "none",
   "filter":{
      "type":"and",
      "fields":[
         {
            "type":"in",
            "dimension":"taskId",
            "values":[
               "184410"
            ]
         },
         
         {
           "type": "selector",
           "dimension": "errorType",
           "value": "DNS",
         }
      ]
   },
   "aggregations":[
      {
         "type":"count",
         "name":"count"
      },
      {
         "type":"longSum",
         "name":"value",
         "expression": "if (errorType == 'DNS', 1, 0)"
      },
      {
        "type": "filtered",
        "aggregator": {
          "type": "count",
          "name": "filtered_aggregation"
        },
        "filter": {
          "type": "selector",
          "dimension": "errorType",
          "value": "DNS"
        },
        "name": "filtered_aggregation"
      }
   ]
}
```

Produces this
![image](https://user-images.githubusercontent.com/49689081/116623430-148d6300-a8fb-11eb-83fe-d41c98ac5a56.png)

The second and third columns should have same values.

**Comment by bbecker-te** [comment] 2021-04-29 22:26
We have a workaround:

Instead of using this expression
`if (errorType == 'DNS', 1, 0)`
use
`array_to_string( if ('DNS' == errorType, 1, 0),'')`

**Comment by clintropolis** [comment] 2021-04-30 03:04
Ok, so it appears the original issue described in this ticket is no longer an issue, I added test cases in current master branch and they all pass when backed with both in memory realtime segments and memory mapped historical segments.

I can however reproduce your example of using an 'if' statement on a string column in a sum aggregator with realtime segments, which is a slightly different (but very similar) issue and a bug in the current version.

The cause of this bug is that for realtime data, since all string columns in Druid could potentially become multi-valued string columns if a new row is added during ingestion processing, callers cannot be certain that your 'errorType' column is not a multi-valued string dimension. So to be safe, the value selector rewrites the expression to something like

```
map((errorType) -> if (errorType == 'DNS', 1, 0), errorType)
```
which ends up producing `[1]` or `[0]` instead of `1` or `0`. This is fine when being used as a selector, because currently all multi-valued outputs are coerced back to string values when aggregated on in a group by or topN, but as an input to aggregators that are not expecting to handle multi-valued input, they do not know what to do with them and so they are treated as 0. I should be able to have a fix for this sometime soon, and will be sure to get it in by the next release (0.22).

Thanks for the report! (and apologies for the bug)

**Comment by clintropolis** [comment] 2021-04-30 03:12
btw, the workaround works, even though it is very odd, because by using an array expression explicitly the selector assumes that the expression is prepared for errorType to be multi-valued string column and skips the transformation (even though in this case the usage doesn't make much sense, but it isn't smart enough yet to understand that). Because Druid string columns can switch between being stored as single valued and multi-valued columns from segment to segment, all array functions allow scalar inputs to be implicitly converted to an array with a single element, so the array function ends up just passing through the result.

This is pretty sub-optimal though as you can imagine, so I'll try to get a real fix in soon 😅

**Comment by clintropolis** [comment] 2021-04-30 05:33
I've created #11185 which adds tests for both issues described here, and fixes the issue in the comments.

**Closed** 2021-05-17 18:59 UTC
Labels: Area - Querying
