### ISSUE TITLE
Flaky UT: RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask

### ISSUE THREAD

**Issue by paul-rogers** [apache/druid#12866] opened 2022-08-05 01:32 UTC
The UT `RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask` failed in [this build](https://app.travis-ci.com/github/apache/druid/jobs/578832603):

```text
[ERROR] Tests run: 29, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 72.402 s <<< FAILURE! - in org.apache.druid.indexing.overlord.RemoteTaskRunnerTest
[ERROR] org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask  Time elapsed: 0.271 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testRunPendingTaskFailToAssignTask(RemoteTaskRunnerTest.java:576)
```

It is evidently known that this test is flaky:

```java
  // higher timeout to reduce flakiness on CI pipeline
```

The same test passes when run on a Mac in the IDE. The test passed in earlier builds on Travis in this branch. The branch in question changed only SQL classes, but nothing in the Overlord. Conclusion: flaky test.

**Comment by abhishekagarwal87** [comment] 2022-11-07 08:24
Duplicate of https://github.com/apache/druid/issues/12643

**Closed by abhishekagarwal87** 2022-11-07 08:24 UTC
Labels: Flaky test
