### ISSUE TITLE
Error with string STRING_TO_MV(str1, str2) in 0.22.1 druid version 

### ISSUE THREAD

**Issue by NikitaElmanov** [apache/druid#12617] opened 2022-06-08 07:01 UTC
Hello!
I'd like to execute **select STRING_TO_MV('sd,sd,ds,ds,ds,sd,ds', ',')** for testing, but it does work with next message:
_Error: Unknown exception
[Ljava.lang.String; cannot be cast to java.lang.String
java.lang.ClassCastException_

**Comment by kfaraz** [comment] 2022-06-08 07:25
The query seems fine and works for me. 
Could you please share some more info? Maybe a screenshot of your console and the query HTTP request and response.

**Comment by NikitaElmanov** [comment] 2022-06-08 07:28
@kfaraz thanks for answer!
<img width="1017" alt="Снимок экрана 2022-06-08 в 10 27 46" src="https://user-images.githubusercontent.com/39399744/172557609-703efa5d-1eab-4689-80f6-a5b21d8fe723.png">

**Comment by kfaraz** [comment] 2022-06-08 08:15
Hmm. Do you see any more details in the logs of the broker service?

**Comment by NikitaElmanov** [comment] 2022-06-08 08:22
Well, some message exists but I guess it's not helpfull. Below content of **/root/apache-druid-0.22.1/var/sv/broker.log**:
_WARN [sql[54e4ea49-0d2f-49e7-b8a9-c36a1089cf89]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT STRING_TO_MV('asdad,sd,dsdsds,sdds,dsdssdds', ',')', resultFormat=array, header=true, context={sqlOuterLimit=101}, parameters=[]}
java.lang.ClassCastException: null_

**Comment by NikitaElmanov** [comment] 2022-06-08 13:35
@kfaraz, is function STRING_TO_MV working for you?
If yes, can you attach screenshot as i've made?

**Comment by kfaraz** [comment] 2022-06-08 13:37
@NikitaElmanov , which version of Druid are you using?

**Comment by kfaraz** [comment] 2022-06-08 13:47
I was able to reproduce the same issue on 0.22.1.
This is a known issue which has been fixed in #12025 and will be released in the upcoming Druid 0.23.0.

**Comment by NikitaElmanov** [comment] 2022-06-08 13:58
Ok, When will you plan to release 0.23.0 version?
How, can I download druid version 0.23.0 and above?

**Comment by kfaraz** [comment] 2022-06-08 14:01
The release candidate is ready and up for voting. If it passes the voting, it will be released soon.
Once it is released, you should be able to download it from the official Apache Druid downloads page.

**Closed** 2022-06-08 14:18 UTC
Labels: Area - SQL

**Comment by NikitaElmanov** [comment] 2022-06-14 04:53
Hi, @kfaraz!
0.23 druid version is a next release?

**Comment by kfaraz** [comment] 2022-06-22 10:25
Yes, @NikitaElmanov, it's the upcoming Druid release. The release candidate has already been voted on. It should be available for download soon.

**Comment by kfaraz** [comment] 2022-06-24 03:07
@NikitaElmanov , you can now download the latest Druid version (0.23.0) from here:
https://druid.apache.org/downloads.html
