### ISSUE TITLE
real time node lead to wrong result(empty result) for the request with regexp filter when real time node is ingesting kafka msg.

### ISSUE THREAD

**Issue by res-life** [apache/druid#1014] opened 2015-01-06 09:43 UTC
increase the kafka message send speed gradually, real time query result will be wrong for the request with regex filter.
request is:

```
"filter": {
    "type": "regex",
    "dimension": "sub5",
    "pattern": "B"
}
...
"orderBy": {
    "type": "default",
    "columns": [
        {
            "dimension": "clicks",
            "direction": "DESCENDING"
        }
    ],
    "limit": 3
}
```

result is:
    [ {
      "version" : "v1",
      "timestamp" : "2015-01-06T05:37:00.000Z",
      "event" : {
        "clicks" : 28
      }
    }, {
      "version" : "v1",
      "timestamp" : "2015-01-06T05:37:00.000Z",
      "event" : {
        "clicks" : 3,
        "sub5" : "BB1"
      }
    }
    ...
    ]
Note, I did not send empty value for the dimension I queried. But result show one null value for the sub5 dimension.
query later, the empty result disappear. It seems thread race condition leads to this error.
If not solve the problem, druid will not be really real time system.
both tested on 0.6.121.1 and 0.6.160

**Comment by fjy** [comment] 2015-01-07 03:09
@res-life Just to be clear, is the error around the result
{
"version" : "v1",
"timestamp" : "2015-01-06T05:37:00.000Z",
"event" : {
"clicks" : 28
}

showing up initially and then disappearing later on in the query?

**Comment by res-life** [comment] 2015-01-07 03:25
{
"event" : {
   //  not have sub5 dimension. All the sub5 value in Kafka Msg is not empty. 
"clicks" : 28
}

The query is same, but the result is different. At first have null sub5 dimension when ingesting, later on this result is:
{
"clicks" : 3,
"sub5" : "BB1"
}

**Comment by fjy** [comment] 2015-01-07 03:37
@res-life I believe others in the community have hit this problem and #995 fixes it.

**Comment by res-life** [comment] 2015-01-07 05:52
@fjy seems not the same problem.
I specified the regexp filter:
      "filter": {
           "type": "regex",
            "dimension": "sub5",
            "pattern": "B"
       }
but result is:
      "event" : {
             // not have sub5 dimension. All the sub5 value in Kafka Msg is not empty. 
             "clicks" : 28
        }
it's not functional issue but performance issue. Only occurs under high throughput ingesting.

**Comment by cheddar** [comment] 2015-01-28 05:04
Is this query a topN query?  A groupBy?

**Comment by res-life** [comment] 2015-02-11 03:14
it's groupBy query

**Comment by vogievetsky** [comment] 2019-06-09 04:48
I think this has been addressed. If not I think it should be a 0.15.0 release blocker. @jihoonson

**Comment by jihoonson** [comment] 2019-06-09 05:00
Since the first RC is about to come out, I think only regression bugs or very critical bugs could be release blockers. This issue looks related to the real time node which is deprecated and should be removed in the near future. I think we can just remove the real time node in 0.16.0.

**Comment by xvrl** [comment] 2022-02-24 18:42
closing, since real-time nodes were removed in 0.16

**Closed by xvrl** 2022-02-24 18:42 UTC
Labels: Bug
