### ISSUE TITLE
Metadata store query performance degrades as the tasks in druid_tasks table grows

### ISSUE THREAD

**Issue by lokesh-lingarajan** [apache/druid#12318] opened 2022-03-08 06:27 UTC
We are currently running a large number of tasks (~1k) in our production and we have started seeing metadata store network throughput increase by 3x as we fetch tasks in UI console and hence degrading performance. This is because the data model for druid_tasks does not have task status as an individual column instead its embedded inside the payload. Because of this model, UI fetches all of the tasks, parses them and then filters out in the widgets.

Faster approach to this solution is in UI, either restrict period refresh in UI or fetch a limited number of rows(that covers running list of tasks). A more longer approach is to solve the data model in the metadata store and let the filter happen at the metadata store itself. The second solution is more involved.

**Comment by lokesh-lingarajan** [comment] 2022-03-08 23:46
PR for solving the above issue in UI - https://github.com/apache/druid/pull/12321

**Comment by abhishekagarwal87** [comment] 2022-04-09 06:39
@lokesh-lingarajan - This PR might help with the cause https://github.com/apache/druid/pull/12404

**Comment by abhishekagarwal87** [comment] 2022-09-08 10:55
Fixed by #12404

**Closed** 2022-09-08 10:55 UTC
